# Generated by Django 6.0 on 2026-01-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
