# Generated by Django 6.0 on 2026-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_orders_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
