# Generated by Django 6.0 on 2026-01-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_alter_orders_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_from_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=200)),
                ('Order', models.IntegerField()),
                ('file', models.IntegerField()),
            ],
        ),
    ]
