# Generated by Django 6.0 on 2026-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_order_from_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_from_offer',
            name='file',
        ),
        migrations.AlterField(
            model_name='order_from_offer',
            name='Order',
            field=models.CharField(max_length=200),
        ),
    ]
