# Generated by Django 6.0 on 2026-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='offer', max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
